import type { StrategyMarketplaceItem } from "@/types/trading";

export const STRATEGY_MARKETPLACE: StrategyMarketplaceItem[] = [
  {
    id: "rsi",
    nameEn: "RSI Mean-Reversion Bands",
    nameAr: "نطاقات RSI للعودة للمتوسط",
    descriptionEn: "Buy oversold / sell overbought using RSI(14) with trend filter.",
    descriptionAr: "شراء عند تشبع بيع / بيع عند تشبع شراء باستخدام RSI(14) مع فلتر اتجاه.",
    bestMarket: "US stocks, crypto",
    winRate: 58,
    totalReturnPct: 12.4,
    maxDrawdownPct: 8.2,
    riskReward: 1.6,
    strengthsEn: ["Clear rules", "Works in ranges"],
    strengthsAr: ["قواعد واضحة", "فعّال في النطاقات"],
    weaknessesEn: ["Fails in strong trends"],
    weaknessesAr: ["ضعيف في الاتجاهات القوية"],
  },
  {
    id: "macd",
    nameEn: "MACD Crossover",
    nameAr: "تقاطع MACD",
    descriptionEn: "Signal line cross with histogram confirmation.",
    descriptionAr: "تقاطع خط الإشارة مع تأكيد الهistogram.",
    bestMarket: "Indices, large caps",
    winRate: 54,
    totalReturnPct: 15.1,
    maxDrawdownPct: 11.5,
    riskReward: 1.4,
    strengthsEn: ["Trend capture", "Widely used"],
    strengthsAr: ["التقاط الاتجاه", "مستخدم على نطاق واسع"],
    weaknessesEn: ["Lag in fast markets"],
    weaknessesAr: ["تأخر في الأسواق السريعة"],
  },
  {
    id: "ma_cross",
    nameEn: "Moving Average Crossover",
    nameAr: "تقاطع المتوسطات المتحركة",
    descriptionEn: "Golden/death cross on 50/200 SMA.",
    descriptionAr: "تقاطع ذهبي/موت على SMA 50/200.",
    bestMarket: "ETFs, Saudi large caps",
    winRate: 52,
    totalReturnPct: 18.3,
    maxDrawdownPct: 14.0,
    riskReward: 1.8,
    strengthsEn: ["Simple", "Long-term bias"],
    strengthsAr: ["بسيط", "اتجاه طويل الأجل"],
    weaknessesEn: ["Whipsaws in chop"],
    weaknessesAr: ["إشارات خاطئة في التذبذب"],
  },
  {
    id: "momentum",
    nameEn: "Momentum Breakout",
    nameAr: "زخم الاختراق",
    descriptionEn: "Rank by 3-month return + volume surge.",
    descriptionAr: "ترتيب حسب عائد 3 أشهر + ارتفاع الحجم.",
    bestMarket: "US growth, crypto",
    winRate: 49,
    totalReturnPct: 22.7,
    maxDrawdownPct: 18.5,
    riskReward: 2.1,
    strengthsEn: ["Captures leaders"],
    strengthsAr: ["يلتقط القادة"],
    weaknessesEn: ["High drawdown"],
    weaknessesAr: ["تراجع مرتفع"],
  },
  {
    id: "mean_reversion",
    nameEn: "Mean Reversion",
    nameAr: "العودة للمتوسط",
    descriptionEn: "Z-score vs 20-day mean with volatility cap.",
    descriptionAr: "Z-score مقابل متوسط 20 يوم مع سقف تقلب.",
    bestMarket: "Forex majors, commodities",
    winRate: 61,
    totalReturnPct: 9.8,
    maxDrawdownPct: 6.5,
    riskReward: 1.3,
    strengthsEn: ["Stable in ranges"],
    strengthsAr: ["مستقر في النطاقات"],
    weaknessesEn: ["Trend risk"],
    weaknessesAr: ["مخاطر الاتجاه"],
  },
  {
    id: "breakout",
    nameEn: "Range Breakout",
    nameAr: "اختراق النطاق",
    descriptionEn: "Enter on close above N-day high with ATR stop.",
    descriptionAr: "دخول عند إغلاق فوق أعلى N يوم مع وقف ATR.",
    bestMarket: "Commodities, small caps",
    winRate: 47,
    totalReturnPct: 19.5,
    maxDrawdownPct: 16.2,
    riskReward: 2.0,
    strengthsEn: ["Asymmetric payoff"],
    strengthsAr: ["عائد غير متماثل"],
    weaknessesEn: ["False breakouts"],
    weaknessesAr: ["اختراقات كاذبة"],
  },
  {
    id: "news_sentiment",
    nameEn: "News Sentiment",
    nameAr: "مزاج الأخبار",
    descriptionEn: "Trade direction from aggregated headline NLP score.",
    descriptionAr: "اتجاه من درجة NLP للعناوين.",
    bestMarket: "Event-driven equities",
    winRate: 55,
    totalReturnPct: 11.2,
    maxDrawdownPct: 9.0,
    riskReward: 1.5,
    strengthsEn: ["Event alpha"],
    strengthsAr: ["ألفا الأحداث"],
    weaknessesEn: ["Needs live news API"],
    weaknessesAr: ["يتطلب API أخبار"],
  },
  {
    id: "ai_hybrid",
    nameEn: "AI Hybrid Ensemble",
    nameAr: "مجموعة AI هجينة",
    descriptionEn: "Multi-agent consensus + technical + macro weighting.",
    descriptionAr: "إجماع متعدد الوكلاء + تقني + أوزان ماكرو.",
    bestMarket: "All asset classes",
    winRate: 63,
    totalReturnPct: 24.1,
    maxDrawdownPct: 10.8,
    riskReward: 2.3,
    strengthsEn: ["Explainable", "Adaptive"],
    strengthsAr: ["قابل للتفسير", "تكيفي"],
    weaknessesEn: ["Complex tuning"],
    weaknessesAr: ["ضبط معقد"],
  },
];

export function getStrategyMarketplace(): StrategyMarketplaceItem[] {
  return STRATEGY_MARKETPLACE;
}

export function getStrategyById(id: string): StrategyMarketplaceItem | undefined {
  return STRATEGY_MARKETPLACE.find((s) => s.id === id);
}
