export interface ProviderCostRow {
  id: string;
  providerEn: string;
  providerAr: string;
  coverageEn: string;
  coverageAr: string;
  marketEn: string;
  marketAr: string;
  liveData: boolean;
  historicalData: boolean;
  freeTierEn: string;
  freeTierAr: string;
  paidTierEn: string;
  paidTierAr: string;
  estimatedMonthlyUsd: number;
  prosEn: string[];
  prosAr: string[];
  consEn: string[];
  consAr: string[];
  recommendedUsageEn: string;
  recommendedUsageAr: string;
}

export const PROVIDER_COST_TABLE: ProviderCostRow[] = [
  {
    id: "polygon",
    providerEn: "Polygon.io",
    providerAr: "Polygon.io",
    coverageEn: "US stocks, options, crypto, indices",
    coverageAr: "أسهم أمريكية، خيارات، crypto، مؤشرات",
    marketEn: "US Stocks",
    marketAr: "أسهم أمريكية",
    liveData: true,
    historicalData: true,
    freeTierEn: "5 calls/min free tier",
    freeTierAr: "5 طلبات/دقيقة مجاناً",
    paidTierEn: "Starter $29/mo · Developer $99/mo",
    paidTierAr: "Starter 29$/شهر",
    estimatedMonthlyUsd: 99,
    prosEn: ["Low latency", "WebSocket", "Institutional grade US"],
    prosAr: ["زمن استجابة منخفض", "WebSocket", "US مؤسسي"],
    consEn: ["US-centric", "Key required"],
    consAr: ["مركز على US", "يتطلب مفتاح"],
    recommendedUsageEn: "Primary US real-time quotes",
    recommendedUsageAr: "أسعار US لحظية أساسية",
  },
  {
    id: "finnhub",
    providerEn: "Finnhub",
    providerAr: "Finnhub",
    coverageEn: "US/global stocks, news, fundamentals",
    coverageAr: "أسهم، أخبار، أساسيات",
    marketEn: "US + News",
    marketAr: "US + أخبار",
    liveData: true,
    historicalData: true,
    freeTierEn: "60 calls/min free",
    freeTierAr: "60 طلب/دقيقة",
    paidTierEn: "Premium from $50/mo",
    paidTierAr: "Premium من 50$/شهر",
    estimatedMonthlyUsd: 50,
    prosEn: ["News + fundamentals bundle", "Good free tier"],
    prosAr: ["أخبار + أساسيات", "طبقة مجانية جيدة"],
    consEn: ["Rate limits on free"],
    consAr: ["حدود على المجاني"],
    recommendedUsageEn: "Secondary US + news primary",
    recommendedUsageAr: "US ثانوي + أخبار أساسي",
  },
  {
    id: "yahoo",
    providerEn: "Yahoo Finance",
    providerAr: "Yahoo Finance",
    coverageEn: "Global equities, forex, commodities, Saudi .SR",
    coverageAr: "أسهم عالمية، فوركس، سلع، سعودي",
    marketEn: "Global + Saudi backup",
    marketAr: "عالمي + سعودي احتياطي",
    liveData: true,
    historicalData: true,
    freeTierEn: "Public — no key",
    freeTierAr: "عام — بدون مفتاح",
    paidTierEn: "N/A",
    paidTierAr: "غير متاح",
    estimatedMonthlyUsd: 0,
    prosEn: ["Free", "Broad coverage", "Saudi .SR"],
    prosAr: ["مجاني", "تغطية واسعة", "سعودي .SR"],
    consEn: ["Delayed ~15min", "Unofficial API"],
    consAr: ["متأخر ~15 دقيقة", "API غير رسمي"],
    recommendedUsageEn: "Backup + Saudi secondary",
    recommendedUsageAr: "احتياطي + سعودي ثانوي",
  },
  {
    id: "binance",
    providerEn: "Binance",
    providerAr: "Binance",
    coverageEn: "Crypto spot/futures public",
    coverageAr: "Crypto عام",
    marketEn: "Crypto",
    marketAr: "Crypto",
    liveData: true,
    historicalData: true,
    freeTierEn: "1200 req/min public",
    freeTierAr: "1200 طلب/دقيقة",
    paidTierEn: "N/A for public data",
    paidTierAr: "N/A",
    estimatedMonthlyUsd: 0,
    prosEn: ["Real-time crypto", "High rate limits"],
    prosAr: ["Crypto لحظي", "حدود عالية"],
    consEn: ["Crypto only"],
    consAr: ["Crypto فقط"],
    recommendedUsageEn: "Primary crypto quotes",
    recommendedUsageAr: "أسعار crypto أساسية",
  },
  {
    id: "coingecko",
    providerEn: "CoinGecko",
    providerAr: "CoinGecko",
    coverageEn: "Crypto market cap, prices",
    coverageAr: "أسعار crypto",
    marketEn: "Crypto",
    marketAr: "Crypto",
    liveData: true,
    historicalData: true,
    freeTierEn: "10-30 calls/min demo",
    freeTierAr: "10-30 طلب/دقيقة",
    paidTierEn: "Analyst $129/mo",
    paidTierAr: "Analyst 129$/شهر",
    estimatedMonthlyUsd: 0,
    prosEn: ["Wide token coverage"],
    prosAr: ["تغطية tokens واسعة"],
    consEn: ["Rate limits", "Slower than Binance"],
    consAr: ["حدود", "أبطأ من Binance"],
    recommendedUsageEn: "Crypto secondary + metadata",
    recommendedUsageAr: "Crypto ثانوي",
  },
  {
    id: "tadawul",
    providerEn: "Tadawul Licensed",
    providerAr: "تداول مرخص",
    coverageEn: "Saudi equities official",
    coverageAr: "أسهم سعودية رسمية",
    marketEn: "Saudi",
    marketAr: "السعودية",
    liveData: true,
    historicalData: true,
    freeTierEn: "Requires licensed agreement",
    freeTierAr: "يتطلب اتفاقية مرخصة",
    paidTierEn: "Enterprise pricing",
    paidTierAr: "تسعير مؤسسي",
    estimatedMonthlyUsd: 500,
    prosEn: ["Official Saudi data", "Compliance"],
    prosAr: ["بيانات رسمية", "امتثال"],
    consEn: ["License required", "Not self-serve"],
    consAr: ["ترخيص مطلوب"],
    recommendedUsageEn: "Primary Saudi when licensed",
    recommendedUsageAr: "سعودي أساسي عند الترخيص",
  },
  {
    id: "twelve_data",
    providerEn: "Twelve Data",
    providerAr: "Twelve Data",
    coverageEn: "Stocks, forex, crypto, ETFs",
    coverageAr: "أسهم، فوركس، crypto",
    marketEn: "Forex + US backup",
    marketAr: "فوركس + US احتياطي",
    liveData: true,
    historicalData: true,
    freeTierEn: "800 calls/day",
    freeTierAr: "800 طلب/يوم",
    paidTierEn: "Grow $29/mo",
    paidTierAr: "Grow 29$/شهر",
    estimatedMonthlyUsd: 29,
    prosEn: ["Multi-asset", "Simple API"],
    prosAr: ["متعدد الأصول", "API بسيط"],
    consEn: ["Daily limits on free"],
    consAr: ["حدود يومية"],
    recommendedUsageEn: "Forex secondary, US fourth",
    recommendedUsageAr: "فوركس ثانوي",
  },
  {
    id: "alpha_vantage",
    providerEn: "Alpha Vantage",
    providerAr: "Alpha Vantage",
    coverageEn: "Stocks, forex, commodities",
    coverageAr: "أسهم، فوركس، سلع",
    marketEn: "Backup global",
    marketAr: "احتياطي عالمي",
    liveData: true,
    historicalData: true,
    freeTierEn: "25 calls/day free",
    freeTierAr: "25 طلب/يوم",
    paidTierEn: "Premium $49/mo",
    paidTierAr: "Premium 49$/شهر",
    estimatedMonthlyUsd: 49,
    prosEn: ["Commodities + forex"],
    prosAr: ["سلع + فوركس"],
    consEn: ["Very low free quota"],
    consAr: ["حصة مجانية منخفضة"],
    recommendedUsageEn: "Tertiary backup only",
    recommendedUsageAr: "احتياطي ثالث فقط",
  },
];

export function getProviderCostTable() {
  return PROVIDER_COST_TABLE;
}
