/** Maps internal symbols to Yahoo Finance tickers for live quotes/candles. */
const YAHOO_TICKERS: Record<string, string> = {
  AAPL: "AAPL",
  MSFT: "MSFT",
  GOOGL: "GOOGL",
  TSLA: "TSLA",
  NVDA: "NVDA",
  AMZN: "AMZN",
  META: "META",
  JPM: "JPM",
  KO: "KO",
  XOM: "XOM",
  V: "V",
  MA: "MA",
  WMT: "WMT",
  DIS: "DIS",
  NFLX: "NFLX",
  AMD: "AMD",
  INTC: "INTC",
  BAC: "BAC",
  PFE: "PFE",
  CVX: "CVX",
  SPY: "SPY",
  QQQ: "QQQ",
  IWM: "IWM",
  VTI: "VTI",
  EEM: "EEM",
  GLD: "GLD",
  GLDM: "GLDM",
  XLE: "XLE",
  USO: "USO",
  BNO: "BNO",
  XLF: "XLF",
  ARKK: "ARKK",
  BP: "BP",
  SAP: "SAP.DE",
  TM: "TM",
  BABA: "BABA",
  NVO: "NVO",
  ASML: "ASML",
  HSBA: "HSBC",
  SHEL: "SHEL",
  "2222": "2222.SR",
  "1120": "1120.SR",
  "1180": "1180.SR",
  "2010": "2010.SR",
  "7010": "7010.SR",
  "1211": "1211.SR",
  "2020": "2020.SR",
  "2082": "2082.SR",
  "1010": "1010.SR",
  "4030": "4030.SR",
  "2280": "2280.SR",
  "2350": "2350.SR",
  BTCUSD: "BTC-USD",
  ETHUSD: "ETH-USD",
  SOLUSD: "SOL-USD",
  BNBUSD: "BNB-USD",
  XRPUSD: "XRP-USD",
  ADAUSD: "ADA-USD",
  DOGEUSD: "DOGE-USD",
  AVAXUSD: "AVAX-USD",
  EURUSD: "EURUSD=X",
  GBPUSD: "GBPUSD=X",
  USDJPY: "USDJPY=X",
  AUDUSD: "AUDUSD=X",
  USDCAD: "USDCAD=X",
  USDCHF: "USDCHF=X",
  CLUSD: "CL=F",
  GCUSD: "GC=F",
  SIUSD: "SI=F",
  NGUSD: "NG=F",
  HGUSD: "HG=F",
  SPX: "^GSPC",
  DJI: "^DJI",
  IXIC: "^IXIC",
  RUT: "^RUT",
  TASI: "^TASI.SR",
  VIX: "^VIX",
};

export function resolveYahooTicker(symbol: string): string {
  const key = symbol.toUpperCase().replace(/\.SR$/i, "");
  return YAHOO_TICKERS[key] ?? YAHOO_TICKERS[symbol.toUpperCase()] ?? symbol;
}

export function parseForexPair(symbol: string): { from: string; to: string } | null {
  const s = symbol.toUpperCase();
  if (s.length !== 6) return null;
  return { from: s.slice(0, 3), to: s.slice(3, 6) };
}

export const LIVE_PROBE_SYMBOLS = {
  usStock: "AAPL",
  saudi: "2222",
  crypto: "BTCUSD",
  forex: "EURUSD",
  commodity: "CLUSD",
  index: "SPX",
  etf: "SPY",
} as const;
