import type { Competitor, ComparisonMatrixRow, CompetitorFilterTag, GapItem, RoadmapPhase } from "./types";

function c(
  base: Omit<Competitor, "matrix"> & {
    matrix: Omit<ComparisonMatrixRow, "platform" | "platformAr" | "isHusai">;
  }
): Competitor {
  return base;
}

export const COMPETITORS: Competitor[] = [
  c({
    id: "tradingview", name: "TradingView", nameAr: "TradingView",
    category: "Charting & Social", categoryAr: "رسوم بيانية واجتماعي",
    mainFeatures: ["Advanced charting", "Pine Script", "Social ideas", "Screeners"],
    mainFeaturesAr: ["رسوم متقدمة", "Pine Script", "أفكار اجتماعية", "فلاتر"],
    strengths: ["Industry-leading charts", "Huge community", "Global asset coverage"],
    strengthsAr: ["رسوم رائدة", "مجتمع ضخم", "تغطية عالمية"],
    weaknesses: ["Limited native AI", "Partial Arabic", "No Tadawul focus"],
    weaknessesAr: ["AI محدود", "عربية جزئية", "بدون تركيز تداول"],
    targetUsers: "Retail & professional traders", targetUsersAr: "متداolon أفراد ومحترفون",
    pricingType: "freemium",
    learnFrom: "Chart UX and indicator ecosystem", learnFromAr: "تجربة الرسوم ونظام المؤشرات",
    husaiOpportunity: "Arabic-first AI on charting parity", husaiOpportunityAr: "AI عربي مع رسوم تنافسية",
    filters: ["charting", "market_research"],
    matrix: { charting: true, aiSignals: false, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: false, paperTrading: false, husaiOpportunity: "Bilingual AI + Saudi", husaiOpportunityAr: "AI ثنائي + سعودي" },
  }),
  c({
    id: "bloomberg", name: "Bloomberg Terminal", nameAr: "بلومبرغ تيرمنال",
    category: "Enterprise Data", categoryAr: "بيانات مؤسسية",
    mainFeatures: ["Real-time data", "News terminal", "Analytics", "Messaging"],
    mainFeaturesAr: ["بيانات لحظية", "أخبار", "تحليلات", "رسائل"],
    strengths: ["Gold standard data", "Institutional trust", "Deep fundamentals"],
    strengthsAr: ["بيانات مرجعية", "ثقة مؤسسية", "أساسيات عميقة"],
    weaknesses: ["Very expensive", "Steep learning curve", "Not retail-friendly"],
    weaknessesAr: ["مكلف جداً", "منحنى تعلم حاد", "ليس للأفراد"],
    targetUsers: "Institutions & funds", targetUsersAr: "مؤسسات وصناديق",
    pricingType: "enterprise",
    learnFrom: "Data depth and news integration", learnFromAr: "عمق البيانات ودمج الأخبار",
    husaiOpportunity: "Affordable Arabic intelligence for MENA retail", husaiOpportunityAr: "ذكاء عربي بأسعار مناسبة لمنطقة MENA",
    filters: ["enterprise_data", "market_research", "fundamental_analysis"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: true, arabicSupport: false, saudiMarketSupport: true, multiMarketSupport: true, autoTrading: false, paperTrading: false, husaiOpportunity: "MENA retail tier", husaiOpportunityAr: "طبقة تجزئة MENA" },
  }),
  c({
    id: "trade-ideas", name: "Trade Ideas", nameAr: "Trade Ideas",
    category: "AI Signals", categoryAr: "إشارات AI",
    mainFeatures: ["HOLLY AI", "Real-time scans", "Odds maker", "Auto charts"],
    mainFeaturesAr: ["HOLLY AI", "مسح لحظي", "Odds maker", "رسوم تلقائية"],
    strengths: ["Strong AI scanning", "US market focus", "Alert automation"],
    strengthsAr: ["مسح AI قوي", "تركيز أمريكي", "تنبيهات"],
    weaknesses: ["US-centric", "Expensive", "No Arabic"],
    weaknessesAr: ["مركز على أمريكا", "مكلف", "بدون عربية"],
    targetUsers: "Active US day traders", targetUsersAr: "متداولون أمريكيون نشطون",
    pricingType: "paid",
    learnFrom: "AI scan UX and alert workflows", learnFromAr: "تجربة مسح AI والتنبيهات",
    husaiOpportunity: "Multi-market AI signals with Arabic explanations", husaiOpportunityAr: "إشارات AI متعددة الأسواق بشروحات عربية",
    filters: ["ai_signals", "charting"],
    matrix: { charting: true, aiSignals: true, backtesting: false, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: true, paperTrading: false, husaiOpportunity: "Global + AR signals", husaiOpportunityAr: "إشارات عالمية + عربي" },
  }),
  c({
    id: "trendspider", name: "TrendSpider", nameAr: "TrendSpider",
    category: "Technical Automation", categoryAr: "أتمتة فنية",
    mainFeatures: ["Auto trendlines", "Multi-timeframe", "Backtesting", "Bots"],
    mainFeaturesAr: ["خطوط اتجاه تلقائية", "أطر متعددة", "اختبار", "روبوتات"],
    strengths: ["Automation depth", "Pattern recognition", "Backtest tools"],
    strengthsAr: ["أتمتة عميقة", "أنماط", "اختبار"],
    weaknesses: ["Complex for beginners", "US focus", "No Saudi data"],
    weaknessesAr: ["معقد للمبتدئين", "تركيز أمريكي", "بدون بيانات سعودية"],
    targetUsers: "Technical traders", targetUsersAr: "متداolon فنيون",
    pricingType: "paid",
    learnFrom: "Automated TA and backtest UX", learnFromAr: "تحليل فني آلي واختبار",
    husaiOpportunity: "Simpler Arabic TA automation", husaiOpportunityAr: "أتمتة فنية عربية أبسط",
    filters: ["charting", "backtesting", "ai_signals"],
    matrix: { charting: true, aiSignals: true, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: true, paperTrading: false, husaiOpportunity: "Arabic backtest UX", husaiOpportunityAr: "اختبار عربي" },
  }),
  c({
    id: "tickeron", name: "Tickeron", nameAr: "Tickeron",
    category: "AI Signals", categoryAr: "إشارات AI",
    mainFeatures: ["AI robots", "Pattern AI", "ETF tools", "Portfolio wizard"],
    mainFeaturesAr: ["روبوتات AI", "أنماط AI", "ETF", "محفظة"],
    strengths: ["AI branding", "Robot strategies", "ETF coverage"],
    strengthsAr: ["علامة AI", "استراتيجيات", "ETF"],
    weaknesses: ["Mixed accuracy perception", "Limited MENA", "English only"],
    weaknessesAr: ["دقة متفاوتة", "MENA محدود", "إنجليزي فقط"],
    targetUsers: "Retail AI-curious traders", targetUsersAr: "متداolon مهتمون بـ AI",
    pricingType: "freemium",
    learnFrom: "AI robot packaging", learnFromAr: "تغليف روبوتات AI",
    husaiOpportunity: "Transparent confidence scores in Arabic", husaiOpportunityAr: "درجات ثقة شفافة بالعربية",
    filters: ["ai_signals", "backtesting"],
    matrix: { charting: true, aiSignals: true, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: true, paperTrading: false, husaiOpportunity: "Trust + Arabic", husaiOpportunityAr: "ثقة + عربي" },
  }),
  c({
    id: "metatrader5", name: "MetaTrader 5", nameAr: "MetaTrader 5",
    category: "Trading Platform", categoryAr: "منصة تداول",
    mainFeatures: ["Forex/CFD", "EAs", "MQL5", "Multi-asset"],
    mainFeaturesAr: ["فوركس/CFD", "EAs", "MQL5", "متعدد"],
    strengths: ["Global broker standard", "EA ecosystem", "Mobile + desktop"],
    strengthsAr: ["معيار وسطاء", "نظام EA", "جوال وسطح"],
    weaknesses: ["Broker-dependent data", "Complex", "Not analysis-first"],
    weaknessesAr: ["بيانات عبر وسيط", "معقد", "ليس تحليلاً أولاً"],
    targetUsers: "Forex & CFD traders", targetUsersAr: "متداolo فوركس",
    pricingType: "broker_based",
    learnFrom: "Platform extensibility", learnFromAr: "قابلية التوسع",
    husaiOpportunity: "Analysis layer without forced execution", husaiOpportunityAr: "تحليل بدون تنفيذ إجباري",
    filters: ["broker_execution", "backtesting", "charting"],
    matrix: { charting: true, aiSignals: false, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: true, arabicSupport: true, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: true, paperTrading: true, husaiOpportunity: "Paper-only safety", husaiOpportunityAr: "أمان ورقي" },
  }),
  c({
    id: "ninjatrader", name: "NinjaTrader", nameAr: "NinjaTrader",
    category: "Futures & FX", categoryAr: "عقود وFX",
    mainFeatures: ["Advanced charting", "Strategy builder", "Market replay", "Automation"],
    mainFeaturesAr: ["رسوم", "استراتيجيات", "إعادة سوق", "أتمتة"],
    strengths: ["Futures depth", "Replay backtest", "Order flow tools"],
    strengthsAr: ["عقود", "إعادة اختبار", "تدفق أوامر"],
    weaknesses: ["US futures focus", "Desktop-heavy", "No Arabic"],
    weaknessesAr: ["تركيز أمريكي", "سطح مكتب", "بدون عربية"],
    targetUsers: "Futures day traders", targetUsersAr: "متداolo عقود",
    pricingType: "freemium",
    learnFrom: "Market replay backtesting", learnFromAr: "اختبار بإعادة السوق",
    husaiOpportunity: "Replay-style backtest for MENA assets", husaiOpportunityAr: "اختبار إعادة لأصول MENA",
    filters: ["charting", "backtesting", "broker_execution"],
    matrix: { charting: true, aiSignals: false, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: true, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: true, paperTrading: true, husaiOpportunity: "Multi-market replay", husaiOpportunityAr: "إعادة متعددة" },
  }),
  c({
    id: "quantconnect", name: "QuantConnect", nameAr: "QuantConnect",
    category: "Quant Research", categoryAr: "بحث كمي",
    mainFeatures: ["Cloud backtest", "LEAN engine", "Multi-asset", "Live deploy"],
    mainFeaturesAr: ["اختبار سحابي", "LEAN", "متعدد", "نشر"],
    strengths: ["Serious quant stack", "Open LEAN", "Institutional grade"],
    strengthsAr: ["م stack كمي", "LEAN مفتوح", "مؤسسي"],
    weaknesses: ["Developer-only", "Steep curve", "Not retail UX"],
    weaknessesAr: ["للمطورين", "منحنى حاد", "UX غير تجزئة"],
    targetUsers: "Quants & developers", targetUsersAr: "كميون ومطورون",
    pricingType: "freemium",
    learnFrom: "Backtest rigor and reproducibility", learnFromAr: "اختبار صارم وقابلية تكرار",
    husaiOpportunity: "No-code Arabic strategy compare", husaiOpportunityAr: "مقارنة استراتيجيات بدون كود",
    filters: ["backtesting", "ai_signals"],
    matrix: { charting: false, aiSignals: true, backtesting: true, newsAnalysis: false, fundamentalAnalysis: true, riskManagement: true, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: true, paperTrading: true, husaiOpportunity: "Accessible quant", husaiOpportunityAr: "كمي مبسط" },
  }),
  c({
    id: "interactive-brokers", name: "Interactive Brokers", nameAr: "Interactive Brokers",
    category: "Broker + Data", categoryAr: "وسيط + بيانات",
    mainFeatures: ["Global execution", "TWS", "Research", "Portfolio"],
    mainFeaturesAr: ["تنفيذ عالمي", "TWS", "بحث", "محفظة"],
    strengths: ["Low-cost global access", "Professional tools", "Multi-asset"],
    strengthsAr: ["وصول عالمي", "أدوات محترفة", "متعدد"],
    weaknesses: ["Complex UI", "Real execution risk", "Not AI-native"],
    weaknessesAr: ["واجهة معقدة", "مخاطر تنفيذ", "ليس AI"],
    targetUsers: "Advanced global traders", targetUsersAr: "متداolon متقدمون",
    pricingType: "broker_based",
    learnFrom: "Multi-market connectivity", learnFromAr: "اتصال متعدد الأسواق",
    husaiOpportunity: "Analysis-first without execution pressure", husaiOpportunityAr: "تحليل أولاً بدون ضغط تنفيذ",
    filters: ["broker_execution", "market_research"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: true, arabicSupport: false, saudiMarketSupport: true, multiMarketSupport: true, autoTrading: true, paperTrading: true, husaiOpportunity: "Safe paper default", husaiOpportunityAr: "ورقي افتراضي" },
  }),
  c({
    id: "etoro", name: "eToro", nameAr: "eToro",
    category: "Social Trading", categoryAr: "تداول اجتماعي",
    mainFeatures: ["Copy trading", "Social feed", "Crypto", "Stocks CFD"],
    mainFeaturesAr: ["نسخ", "تغذية", "كrypto", "أسهم"],
    strengths: ["Social UX", "Beginner friendly", "Copy trading"],
    strengthsAr: ["UX اجتماعي", "سهل", "نسخ"],
    weaknesses: ["Spread costs", "Limited research depth", "Regulatory variance"],
    weaknessesAr: ["تكاليف", "بحث محدود", "تنظيم متفاوت"],
    targetUsers: "Beginner social traders", targetUsersAr: "مبتدئون اجتماعيون",
    pricingType: "broker_based",
    learnFrom: "Social proof and copy mechanics", learnFromAr: "إثبات اجتماعي ونسخ",
    husaiOpportunity: "Community signals without copy-trade risk", husaiOpportunityAr: "إشارات مجتمع بدون مخاطر نسخ",
    filters: ["social_trading", "broker_execution", "crypto_bots"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: false, arabicSupport: true, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: true, paperTrading: false, husaiOpportunity: "Educational social layer", husaiOpportunityAr: "طبقة اجتماعية تعليمية" },
  }),
  c({
    id: "seeking-alpha", name: "Seeking Alpha", nameAr: "Seeking Alpha",
    category: "Research & News", categoryAr: "بحث وأخبار",
    mainFeatures: ["Stock analysis", "Dividends", "News", "Ratings"],
    mainFeaturesAr: ["تحليل أسهم", "أرباح", "أخبار", "تقييمات"],
    strengths: ["Crowd research", "Fundamental depth", "US equities"],
    strengthsAr: ["بحث جماعي", "أساسيات", "أسهم أمريكية"],
    weaknesses: ["Quality variance", "US focus", "No trading tools"],
    weaknessesAr: ["جودة متفاوتة", "أمريكا", "بدون تداول"],
    targetUsers: "Long-term equity investors", targetUsersAr: "مستثمرون طويل الأجل",
    pricingType: "freemium",
    learnFrom: "Community research model", learnFromAr: "نموذج بحث جماعي",
    husaiOpportunity: "Curated Arabic research + AI summary", husaiOpportunityAr: "بحث عربي + ملخص AI",
    filters: ["fundamental_analysis", "market_research"],
    matrix: { charting: false, aiSignals: false, backtesting: false, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: false, paperTrading: false, husaiOpportunity: "AI + fundamentals AR", husaiOpportunityAr: "AI + أساسيات عربي" },
  }),
  c({
    id: "stock-rover", name: "Stock Rover", nameAr: "Stock Rover",
    category: "Fundamental Screening", categoryAr: "فحص أساسي",
    mainFeatures: ["Screeners", "Portfolio analytics", "Research reports", "Charts"],
    mainFeaturesAr: ["فلاتر", "محفظة", "تقارير", "رسوم"],
    strengths: ["Fundamental screeners", "Portfolio tracking", "US/CA focus"],
    strengthsAr: ["فلاتر أساسية", "تتبع محفظة", "US/CA"],
    weaknesses: ["Limited technical AI", "No crypto depth", "English only"],
    weaknessesAr: ["AI فني محدود", "crypto محدود", "إنجليزي"],
    targetUsers: "Value investors", targetUsersAr: "مستثمرو قيمة",
    pricingType: "paid",
    learnFrom: "Fundamental screener UX", learnFromAr: "UX فلاتر أساسية",
    husaiOpportunity: "Multi-market screeners in Arabic", husaiOpportunityAr: "فلاتر متعددة بالعربية",
    filters: ["fundamental_analysis", "market_research"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: false, fundamentalAnalysis: true, riskManagement: true, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: false, paperTrading: false, husaiOpportunity: "Saudi fundamentals", husaiOpportunityAr: "أساسيات سعودية" },
  }),
  c({
    id: "koyfin", name: "Koyfin", nameAr: "Koyfin",
    category: "Market Research", categoryAr: "بحث سوق",
    mainFeatures: ["Dashboards", "Macro data", "Equity tools", "ETF analysis"],
    mainFeaturesAr: ["لوحات", "ماكرو", "أسهم", "ETF"],
    strengths: ["Beautiful dashboards", "Affordable pro data", "Macro views"],
    strengthsAr: ["لوحات جميلة", "بيانات بأسعار معقولة", "ماكرو"],
    weaknesses: ["Less trading execution", "Limited AI signals", "US-centric"],
    weaknessesAr: ["تنفيذ محدود", "إشارات AI محدودة", "أمريكا"],
    targetUsers: "Investors & analysts", targetUsersAr: "مستثمرون ومحللون",
    pricingType: "freemium",
    learnFrom: "Dashboard design for research", learnFromAr: "تصميم لوحات البحث",
    husaiOpportunity: "Arabic macro dashboards for GCC", husaiOpportunityAr: "لوحات ماكرو عربية لـ GCC",
    filters: ["market_research", "fundamental_analysis", "enterprise_data"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: false, paperTrading: false, husaiOpportunity: "GCC macro focus", husaiOpportunityAr: "تركيز GCC" },
  }),
  c({
    id: "finviz", name: "Finviz", nameAr: "Finviz",
    category: "Screening", categoryAr: "فحص",
    mainFeatures: ["Heat maps", "Screeners", "News", "Charts"],
    mainFeaturesAr: ["خرائط حرارية", "فلاتر", "أخبار", "رسوم"],
    strengths: ["Fast visual screening", "Free tier", "Popular among retail"],
    strengthsAr: ["فحص بصري سريع", "مجاني", "شائع"],
    weaknesses: ["US only", "Dated UI", "No AI explanations"],
    weaknessesAr: ["أمريكا فقط", "واجهة قديمة", "بدون شروحات AI"],
    targetUsers: "US retail scanners", targetUsersAr: "مسح أمريكي",
    pricingType: "freemium",
    learnFrom: "Visual heatmap scanning", learnFromAr: "مسح خرائط حرارية",
    husaiOpportunity: "Visual multi-market scan in Arabic", husaiOpportunityAr: "مسح بصري متعدد بالعربية",
    filters: ["charting", "market_research"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: false, paperTrading: false, husaiOpportunity: "MENA heatmaps", husaiOpportunityAr: "خرائط MENA" },
  }),
  c({
    id: "marketsmith", name: "MarketSmith", nameAr: "MarketSmith",
    category: "CAN SLIM Research", categoryAr: "بحث CAN SLIM",
    mainFeatures: ["IBD ratings", "Stock charts", "Pattern recognition", "Lists"],
    mainFeaturesAr: ["تقييمات IBD", "رسوم", "أنماط", "قوائم"],
    strengths: ["Growth investing framework", "Pattern lists", "Educational"],
    strengthsAr: ["إطار نمو", "قوائم أنماط", "تعليمي"],
    weaknesses: ["US growth only", "Subscription cost", "No Arabic"],
    weaknessesAr: ["نمو أمريكي", "اشتراك", "بدون عربية"],
    targetUsers: "Growth stock investors", targetUsersAr: "مستثمرو نمو",
    pricingType: "paid",
    learnFrom: "Structured investing methodology", learnFromAr: "منهجية استثمار منظمة",
    husaiOpportunity: "Arabic growth methodology for Tadawul", husaiOpportunityAr: "منهجية نمو عربية للتداول",
    filters: ["fundamental_analysis", "market_research"],
    matrix: { charting: true, aiSignals: false, backtesting: false, newsAnalysis: false, fundamentalAnalysis: true, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: false, paperTrading: false, husaiOpportunity: "Tadawul growth lists", husaiOpportunityAr: "قوائم نمو تداول" },
  }),
  c({
    id: "3commas", name: "3Commas", nameAr: "3Commas",
    category: "Crypto Bots", categoryAr: "روبوتات كrypto",
    mainFeatures: ["DCA bots", "Grid bots", "Smart trade", "Portfolio"],
    mainFeaturesAr: ["DCA", "Grid", "Smart trade", "محفظة"],
    strengths: ["Crypto automation", "Exchange integrations", "Bot marketplace"],
    strengthsAr: ["أتمتة crypto", "تكامل بورصات", "سوق روبوتات"],
    weaknesses: ["Execution risk", "Not equities", "Requires exchange keys"],
    weaknessesAr: ["مخاطر تنفيذ", "ليس أسهم", "مفاتيح بورصة"],
    targetUsers: "Crypto bot traders", targetUsersAr: "متداolo روبوتات crypto",
    pricingType: "freemium",
    learnFrom: "Bot strategy templates", learnFromAr: "قوالب روبوتات",
    husaiOpportunity: "Paper-only bot simulation", husaiOpportunityAr: "محاكاة روبوتات ورقية",
    filters: ["crypto_bots", "no_code_automation", "broker_execution"],
    matrix: { charting: true, aiSignals: true, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: true, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: true, paperTrading: false, husaiOpportunity: "Safe bot paper mode", husaiOpportunityAr: "روبوتات ورقية آمنة" },
  }),
  c({
    id: "cryptohopper", name: "Cryptohopper", nameAr: "Cryptohopper",
    category: "Crypto Bots", categoryAr: "روبوتات crypto",
    mainFeatures: ["Trading bots", "Copy bots", "Strategy designer", "Paper trading"],
    mainFeaturesAr: ["روبوتات", "نسخ", "مصمم", "ورقي"],
    strengths: ["No-code bots", "Paper mode", "Marketplace"],
    strengthsAr: ["بدون كود", "ورقي", "سوق"],
    weaknesses: ["Crypto only", "Fees add up", "Security concerns"],
    weaknessesAr: ["crypto فقط", "رسوم", "أمان"],
    targetUsers: "Crypto automators", targetUsersAr: "م automat crypto",
    pricingType: "freemium",
    learnFrom: "No-code strategy designer", learnFromAr: "مصمم بدون كود",
    husaiOpportunity: "Unified paper bots across asset classes", husaiOpportunityAr: "روبوتات ورقية موحدة",
    filters: ["crypto_bots", "no_code_automation", "backtesting"],
    matrix: { charting: true, aiSignals: true, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: true, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: true, paperTrading: true, husaiOpportunity: "Multi-asset paper bots", husaiOpportunityAr: "روبوتات ورقية متعددة" },
  }),
  c({
    id: "coinrule", name: "Coinrule", nameAr: "Coinrule",
    category: "No-code Automation", categoryAr: "أتمتة بدون كود",
    mainFeatures: ["If-this-then-that rules", "Templates", "Multi-exchange", "Demo"],
    mainFeaturesAr: ["قواعد", "قوالب", "بورصات", "تجريبي"],
    strengths: ["Simple rule builder", "Templates", "Beginner friendly"],
    strengthsAr: ["قواعد بسيطة", "قوالب", "سهل"],
    weaknesses: ["Crypto-focused", "Limited stocks", "English UI"],
    weaknessesAr: ["crypto", "أسهم محدود", "إنجليزي"],
    targetUsers: "Rule-based crypto traders", targetUsersAr: "متداolon قواعد crypto",
    pricingType: "freemium",
    learnFrom: "Template-based automation", learnFromAr: "أتمتة بالقوالب",
    husaiOpportunity: "Arabic rule builder for alerts", husaiOpportunityAr: "منشئ قواعد عربي للتنبيهات",
    filters: ["no_code_automation", "crypto_bots"],
    matrix: { charting: false, aiSignals: true, backtesting: true, newsAnalysis: false, fundamentalAnalysis: false, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: true, paperTrading: true, husaiOpportunity: "Alert rules AR", husaiOpportunityAr: "قواعد تنبيه عربي" },
  }),
  c({
    id: "alphasense", name: "AlphaSense", nameAr: "AlphaSense",
    category: "Enterprise Research", categoryAr: "بحث مؤسسي",
    mainFeatures: ["Document search", "AI search", "Earnings", "Expert calls"],
    mainFeaturesAr: ["بحث مستندات", "AI", "أرباح", "خبراء"],
    strengths: ["Enterprise research AI", "Document intelligence", "Wall St grade"],
    strengthsAr: ["AI مؤسسي", "مستندات", "درجة Wall St"],
    weaknesses: ["Enterprise pricing", "Not retail", "No trading"],
    weaknessesAr: ["أسعار مؤسسية", "ليس تجزئة", "بدون تداول"],
    targetUsers: "Analysts & funds", targetUsersAr: "محللون وصناديق",
    pricingType: "enterprise",
    learnFrom: "AI document search UX", learnFromAr: "بحث مستندات AI",
    husaiOpportunity: "Retail Arabic research AI tier", husaiOpportunityAr: "طبقة بحث AI عربية للأفراد",
    filters: ["enterprise_data", "market_research", "ai_signals"],
    matrix: { charting: false, aiSignals: true, backtesting: false, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: false, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: true, autoTrading: false, paperTrading: false, husaiOpportunity: "MENA research AI", husaiOpportunityAr: "بحث AI MENA" },
  }),
  c({
    id: "thinkorswim", name: "Thinkorswim", nameAr: "Thinkorswim",
    category: "Broker Platform", categoryAr: "منصة وسيط",
    mainFeatures: ["Advanced charts", "Paper money", "Scans", "Options"],
    mainFeaturesAr: ["رسوم", "مال ورقي", "مسح", "خيارات"],
    strengths: ["Free with Schwab", "Paper trading", "Pro charts"],
    strengthsAr: ["مجاني مع Schwab", "ورقي", "رسوم محترفة"],
    weaknesses: ["US broker lock-in", "Complex", "No Saudi market"],
    weaknessesAr: ["ربط وسيط أمريكي", "معقد", "بدون سعودي"],
    targetUsers: "US active traders", targetUsersAr: "متداolon أمريكيون",
    pricingType: "broker_based",
    learnFrom: "Paper money integration", learnFromAr: "دمج التداول الورقي",
    husaiOpportunity: "Global paper + Arabic analysis", husaiOpportunityAr: "ورقي عالمي + تحليل عربي",
    filters: ["charting", "backtesting", "broker_execution", "ai_signals"],
    matrix: { charting: true, aiSignals: false, backtesting: true, newsAnalysis: true, fundamentalAnalysis: true, riskManagement: true, arabicSupport: false, saudiMarketSupport: false, multiMarketSupport: false, autoTrading: true, paperTrading: true, husaiOpportunity: "Global multi-market paper", husaiOpportunityAr: "ورقي متعدد عالمي" },
  }),
];

export const HUSAI_MATRIX_ROW: ComparisonMatrixRow = {
  platform: "HUSAI Trading AI",
  platformAr: "HUSAI تداول AI",
  charting: false,
  aiSignals: true,
  backtesting: true,
  newsAnalysis: true,
  fundamentalAnalysis: false,
  riskManagement: true,
  arabicSupport: true,
  saudiMarketSupport: true,
  multiMarketSupport: true,
  autoTrading: false,
  paperTrading: true,
  husaiOpportunity: "Lead with Arabic AI + Saudi + safe paper default",
  husaiOpportunityAr: "قيادة بـ AI عربي + سعودي + ورقي آمن",
  isHusai: true,
};

export const FILTER_LABELS: Record<CompetitorFilterTag, { en: string; ar: string }> = {
  charting: { en: "Charting", ar: "رسوم بيانية" },
  ai_signals: { en: "AI Signals", ar: "إشارات AI" },
  backtesting: { en: "Backtesting", ar: "اختبار استراتيجيات" },
  broker_execution: { en: "Broker Execution", ar: "تنفيذ وسيط" },
  crypto_bots: { en: "Crypto Bots", ar: "روبوتات crypto" },
  market_research: { en: "Market Research", ar: "بحث سوق" },
  fundamental_analysis: { en: "Fundamental Analysis", ar: "تحليل أساسي" },
  social_trading: { en: "Social Trading", ar: "تداول اجتماعي" },
  enterprise_data: { en: "Enterprise Data", ar: "بيانات مؤسسية" },
  no_code_automation: { en: "No-code Automation", ar: "أتمتة بدون كود" },
  saudi_market: { en: "Saudi Market", ar: "السوق السعودي" },
  arabic_support: { en: "Arabic Support", ar: "دعم عربي" },
};

export function filterCompetitors(filters: CompetitorFilterTag[]): Competitor[] {
  if (!filters.length) return COMPETITORS;
  return COMPETITORS.filter((c) => filters.every((f) => c.filters.includes(f)));
}

export function getComparisonMatrix(locale: "ar" | "en" = "en"): ComparisonMatrixRow[] {
  const rows = COMPETITORS.map((c) => ({
    platform: locale === "ar" ? c.nameAr : c.name,
    platformAr: c.nameAr,
    ...c.matrix,
  }));
  const husai = {
    ...HUSAI_MATRIX_ROW,
    platform: locale === "ar" ? HUSAI_MATRIX_ROW.platformAr : HUSAI_MATRIX_ROW.platform,
  };
  return [...rows, husai];
}

export function getFeatureGapAnalysis(): GapItem[] {
  return [
    { id: "charts", priority: "high", titleEn: "Advanced charting workspace", titleAr: "مساحة رسوم متقدمة", descriptionEn: "TradingView-level interactive charts with indicators overlay", descriptionAr: "رسوم تفاعلية بمستوى TradingView مع مؤشرات" },
    { id: "fundamentals", priority: "high", titleEn: "Fundamental data depth", titleAr: "عمق البيانات الأساسية", descriptionEn: "Financial statements and valuation metrics for US + Tadawul", descriptionAr: "قوائم مالية وتقييم لأمريكا والتداول" },
    { id: "strategy-builder", priority: "medium", titleEn: "Visual strategy builder", titleAr: "منشئ استراتيجيات مرئي", descriptionEn: "No-code rules like Coinrule but paper-only", descriptionAr: "قواعد بدون كود مثل Coinrule لكن ورقي فقط" },
    { id: "portfolio", priority: "medium", titleEn: "Full portfolio analytics", titleAr: "تحليلات محفظة كاملة", descriptionEn: "Multi-account tracking like Stock Rover", descriptionAr: "تتبع متعدد مثل Stock Rover" },
    { id: "community", priority: "low", titleEn: "Community signal feed", titleAr: "تغذية إشارات مجتمع", descriptionEn: "Social layer without copy-trade execution", descriptionAr: "طبقة اجتماعية بدون تنفيذ نسخ" },
    { id: "mobile", priority: "low", titleEn: "Native mobile apps", titleAr: "تطبيقات جوال", descriptionEn: "iOS/Android companion apps", descriptionAr: "تطبيقات iOS/Android" },
  ];
}

export function getCompetitiveAdvantages(): GapItem[] {
  return [
    { id: "arabic", priority: "high", titleEn: "Arabic-first AI explanations", titleAr: "شروحات AI عربية أولاً", descriptionEn: "Default RTL UX with bilingual analysis", descriptionAr: "UX RTL افتراضي مع تحليل ثنائي" },
    { id: "saudi", priority: "high", titleEn: "Saudi market specialization", titleAr: "تخصص السوق السعودي", descriptionEn: "Tadawul symbols and macro oil/rates context", descriptionAr: "رموز تداول وسياق نفط/فائدة" },
    { id: "safe", priority: "high", titleEn: "Paper-only by default", titleAr: "ورقي افتراضياً", descriptionEn: "No real execution — compliance locked", descriptionAr: "بدون تنفيذ حقيقي — امتثال مقفل" },
    { id: "multi", priority: "medium", titleEn: "Unified multi-market data", titleAr: "بيانات موحدة متعددة", descriptionEn: "US, crypto, forex, commodities, indices, ETFs in one platform", descriptionAr: "أمريكا، crypto، فوركس، سلع، مؤشرات، ETF في منصة واحدة" },
    { id: "audit", priority: "medium", titleEn: "Recommendation audit trail", titleAr: "سجل تدقيق التوصيات", descriptionEn: "Every AI signal logged with data source", descriptionAr: "كل إشارة AI مسجلة مع مصدر البيانات" },
  ];
}

export const ROADMAP: RoadmapPhase[] = [
  {
    phase: 1,
    titleEn: "Foundation",
    titleAr: "الأساس",
    itemsEn: ["Real market data layer", "Paper trading", "AI explainability AR/EN", "Provider dashboard", "Compliance locked"],
    itemsAr: ["طبقة بيانات حقيقية", "تداول ورقي", "شروحات AI عربي/إنجليزي", "لوحة المزودين", "امتثال مقفل"],
  },
  {
    phase: 2,
    titleEn: "Intelligence Engines",
    titleAr: "محركات الذكاء",
    itemsEn: ["Why Now engine", "What Must Change", "Market Consensus", "Cross-market chains", "AI memory loop"],
    itemsAr: ["محرك لماذا الآن", "ما الذي يجب أن يتغير", "إجماع السوق", "سلاسل الأسواق", "حلقة ذاكرة AI"],
  },
  {
    phase: 3,
    titleEn: "Advanced Analytics",
    titleAr: "تحليلات متقدمة",
    itemsEn: ["Strategy Lab", "Market Health Score", "Scenario simulator", "Opportunity Radar", "Smart money flow"],
    itemsAr: ["مختبر الاستراتيجيات", "درجة صحة السوق", "محاكي السيناريوهات", "رادار الفرص", "تدflow الأموال"],
  },
  {
    phase: 4,
    titleEn: "Differentiation",
    titleAr: "التمايز",
    itemsEn: ["Data Quality Score", "Investment journal", "Portfolio simulator", "Competitor intelligence", "Arabic-first MENA focus"],
    itemsAr: ["درجة جودة البيانات", "سجل الاستثمار", "محاكاة المحفظة", "ذكاء المنافسين", "تركيز MENA عربي أولاً"],
  },
];

export const PRICING_LABELS: Record<Competitor["pricingType"], { en: string; ar: string }> = {
  free: { en: "Free", ar: "مجاني" },
  freemium: { en: "Freemium", ar: "مجاني جزئي" },
  paid: { en: "Paid", ar: "مدفوع" },
  enterprise: { en: "Enterprise", ar: "مؤسسي" },
  broker_based: { en: "Broker-based", ar: "عبر الوسيط" },
};
